### PR TITLE
feat/ change labelLine of arc label from path mark to line mark

### PR DESCRIPTION
**Pull request by pairone**
[[中文版模板 / Chinese template](https://github.com/VisActor/vrender/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Release
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Comment by pairone** [comment]
接入vgrammar,在动画状态下，创建为line图元的label line 动画正常，于text同步
https://github.com/VisActor/VRender/assets/40026218/4e7d4e3e-0572-4fc2-9494-7f2fe84ecfd3

**Comment by pairone** [comment]
support centerOffset

**Comment by pairone** [comment]
[support edge layout](https://github.com/VisActor/VRender/pull/310/commits/1aec786c9bfcc28d19fbed333ce2d052a4b4ead8)
dd9c989b-d5dd-4934-9335-b0ecffe0d3bf

**Comment by pairone** [comment]
Omit when the text exceeds the maximum width of the label
image

**Review by skie1997 — APPROVED** [review]

**Pull request merged**
